# LU分解をしてみよう

LU分解とは，行列を下三角行列(L)上三角行列(U)の積に分解すること．
LU分解を用いることで連立方程式を計算コスト低く計算することができる．
\begin{eqnarray}
    Ax = LUx = b
\end{eqnarray}

まず，
\begin{eqnarray}
    Ly = b ~~ (Ux=y)\\
\end{eqnarray}
で$y$を計算する．その後，
\begin{eqnarray}
    Ux = y
\end{eqnarray}
により，解$x$を計算する．

## $L,U$の成分の計算の仕方
LU分解をすると，元々の行列の$n^2$個の係数から$L,U$の$n(n+1)$個の係数を求めることになるので，LU分解は一意に定まらない．そのため，$L,U$の係数のうち$n$個を固定して，他の$L,U$の係数を計算する．$U$か$L$の対角成分を1にすると計算がしやすく，通常はその方法を使って計算する．
(ここでは$L$の対角成分を1とおく．)

\begin{eqnarray}
    U_{ij} = (A_{ij} - \sum_{k=0}^{i-1} L_{jk} U_{kj})/L_{ii}\\
    L_{ij} = (A_{ij} - \sum_{k=0}^{i-1} L_{jk} U_{kj})/U_{ii}
\end{eqnarray}

$L_{ii}$は1であることが保証されているが，$U_{ii}$は0になる可能性がある．その場合は$L_{ij}$は任意の実数をとりうるので，1とおくことができる．

## 計算コスト
$\sum_{k=0}^{i-1}$の計算($O(n)$)を$n^2$個の変数に対して行っているので，$O(n^3)$である．

> UL分解もありそう？

> 出力$b$が変わる度に，ガウスの消去法では三角行列化するための操作が必要であったが，
> LU分解では一度$L,U$を求めてしまえばそのような操作がいらず，計算コスト$O(n^2)$で解を求めることができる．
> アルゴリズムトータルではLU分解は$O(n^3)$となり，ガウスの消去法と変わらないことに注意．

In [1]:
import numpy as np

def LU_decompostion(matrix):
    length = len(matrix)
    L = np.eye(length)
    U = np.zeros([length,length])
    
    for i in range(length):
        for j in range(i,length):
            sub = sum(L[i][k]*U[k][j] for k in range(i))
            #print(i,j,sub,sub)
            U[i][j] = (matrix[i][j]-sub) / L[i][i]
        for j in range(i+1,length):
            sub = sum(L[j][k]*U[k][i] for k in range(i))
            #print(j,i,sub)
            if U[i][i]!=0:
                L[j][i] = (matrix[j][i]-sub) / U[i][i]
            else:
                L[j][i] = 1.0
    return L,U

## 具体的な行列でLU分解

In [2]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
#matrix = np.array([[1.2,2,3],[5,6,7],[9,10,11]])
#matrix = np.array([[1,2],[3,6]])
print(f"det: {np.linalg.det(matrix)}")
L,U = LU_decompostion(matrix)

print(matrix)
print(L)
print(U)

det: 0.0
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1.  0.  0.  0.]
 [ 5.  1.  0.  0.]
 [ 9.  2.  1.  0.]
 [13.  3.  1.  1.]]
[[  1.   2.   3.   4.]
 [  0.  -4.  -8. -12.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]


In [3]:
L@U==matrix

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [4]:
L@U

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])